package com.dbpilot.core.port.in;

import com.dbpilot.core.model.QueryResult;

/**
 * Inbound port for the primary use case: translating natural language into
 * a database query and optionally executing it.
 *
 * <p>This is the main entry point invoked by both the MCP tool and the CLI.</p>
 *
 * @author DB-Pilot
 */
public interface TranslateQueryUseCase {

    /**
     * Command object for query translation requests.
     *
     * @param userId        the user making the request
     * @param databaseAlias the target database connection alias
     * @param naturalQuery  the natural language description of desired data
     * @param execute       whether to execute the generated query or just return it
     * @param dryRun        whether to run EXPLAIN instead of actual execution
     */
    record TranslateCommand(
            String userId,
            String databaseAlias,
            String naturalQuery,
            boolean execute,
            boolean dryRun
    ) {}

    /**
     * Response object containing the generated query and optional execution results.
     *
     * @param generatedQuery the SQL or aggregation pipeline generated by the LLM
     * @param queryResult    the execution result (null if execute=false)
     * @param explanation    human-readable explanation of the generation process
     */
    record TranslateResponse(
            String generatedQuery,
            QueryResult queryResult,
            String explanation
    ) {}

    /**
     * Translates a natural language query into a database query.
     *
     * <p>Pipeline:</p>
     * <ol>
     *   <li>Load schema metadata (from cache or introspect)</li>
     *   <li>Rank tables by relevance using triple-layer algorithm</li>
     *   <li>Assemble prompt with schema + rules + habits + intent</li>
     *   <li>Enforce token budget via TokenGuard</li>
     *   <li>Send to LLM for query generation</li>
     *   <li>Optionally execute or explain the generated query</li>
     *   <li>Record table access for habit learning</li>
     * </ol>
     *
     * @param command the translation command
     * @return the translation response
     */
    TranslateResponse translate(TranslateCommand command);
}
